### ISSUE TITLE
Add documentation on how to run Security/Best Practices controls locally

### ISSUE THREAD

**Issue by jonathimer** [linuxfoundation/insights#342]
related to https://github.com/linuxfoundation/insights/discussions/341

We have to add better documentation on how maintainers can run security controls locally/with a GitHub action.

**Comment by ssinghlinux1989** [comment]
@jonathimer , Is this info correct about this:
Certainly! Below is a step-by-step procedure designed for maintainers to help improve and standardize documentation on running security controls both locally and via GitHub Actions. This template ensures clarity and precision:

---

## Procedure: Documenting How to Run Security Controls Locally and via GitHub Actions

### Introduction

This guide documents the steps for maintainers to add clear instructions on running project security controls, covering both local environments and GitHub Actions workflows. 

---

### Prerequisites

- Project repository access with write permissions.
- Familiarity with the security controls/tools (e.g., Snyk, Trivy, Bandit, etc.).
- Text editor or IDE to edit documentation files (e.g., README.md or SECURITY.md).

---

### Step 1: Identify the Security Controls

**a.** List all relevant security tools and controls required for the project.  
**Examples:**  
- Dependency vulnerability scanner (Snyk)
- Static analysis tool (Bandit)
- Container/vulnerability scanner (Trivy)

---

### Step 2: Gather Installation and Usage Details

**a.** For each tool, collect:
- Tool installation instructions (package manager, Docker, etc.).
- Typical command-line usage.

---

### Step 3: Create or Update the Documentation Section

**a.** Choose the appropriate place to document:
- `README.md` (for basic instructions)
- `SECURITY.md` (for dedicated security guidance)

**b.** Use clear section headers:

```markdown
## Running Security Controls Locally

## Running Security Controls via GitHub Actions
```

---

### Step 4: Document Local Execution Steps

**a.** For each tool, describe local installation and invocation, for example:

```markdown
### 1. Dependency Scanning with Snyk

#### Local Setup

1. Install [Snyk CLI](https://docs.snyk.io/getting-started/snyk-cli/installation):

    ```sh
    npm install -g snyk
    ```

2. Authenticate (if required):

    ```sh
    snyk auth
    ```

3. Run the security scan:

    ```sh
    snyk test
    ```
```

---

### Step 5: Document GitHub Action Workflow

**a.** Show how to use each tool as part of a GitHub Actions workflow.  
**b.** Reference example workflow file(s):

```markdown
### 2. Dependency Scan in CI/CD (GitHub Actions)

We provide a workflow file at `.github/workflows/security.yml`:

```yaml
name: Security Scan

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
```

**To use:**
1. Ensure a secret named `SNYK_TOKEN` is added in your GitHub repository.
2. Adjust the example to match your project language/environment.
```

---

### Step 6: Validate the Instructions

**a.** Follow the documentation yourself or ask another maintainer to verify clarity and completeness.  
**b.** Update as needed based on feedback.

---

### Step 7: Reference the Documentation

**a.** Link to the security instructions section in relevant locations (e.g., contribution guidelines).

---

### Example Template

Here’s a sample section you can adapt:

```markdown
## Security Controls

### Running Locally

1. Install dependencies:
    ```sh
    pip install bandit
    ```
2. Run Bandit:
    ```sh
    bandit -r your_module/
    ```

### Running via GitHub Actions

An automated Bandit scanundefined
